export class PortfolioLoan {   // Data for portfolio loan grid (and Surveillance by Submarket).  No longer used (should have lots of dynamic columns, so we use Raw instead).

    constructor (
        public portfolio_market_date: string,
        public loan_id_client: string,
        public property_id_client: string,
        public rs_propertyname: string,
        public rs_streetadress: string,
        public rs_city: string,
        public rs_state: string,
        public rs_zipcode: string,
        public region: string,
        public metcode_name: string,
        public subname: string,
        public sector: string,
        public RS_subsector: string,
        public current_balance: string,
        public rs_forecasted_noi_chg_: string,
        public rs_forecasted_value_chg_: string,
        public rs_forecasted_cap_rate_: string,
        public market_data_date: string,
        public loan_type: string,
        public loan_origin_date: string,
        public maturity_date_orig: string,
        public balloon: string,
        public loan_risk_rating: string,
        public client_risk_rating: string,
        public pd_cum: string,
        public ls_cum: string,
        public el_cum: string,
        public el_value: string,
        public debtYield: string,
        public yieldDegradation: string,
        public dscr: string,
        public dscr_date: string,
        public current_ltv: string,
        public ltv_orig: string,
        public amort_term_months: string,
        public amort_type: string,
        public arm_index: string,
        public remaining_term: string,
        public amort_term_remain: string,
        public interest_rate: string,
        public loan_ds_monthly: string,
        public seniority: string,
        public Loan_group_1: string,
        public Loan_group_2: string,
        public portfolio_property_dim_id: number
    )  {}
}
